# Configuration file for SCENIC+
input_loc: /path/to/mdata.h5mu
organism: mouse # human or mouse
outdir:  /path/to/output # Created if doesn't exist.
scratchdir: /cellar/users/aklie/tmp # Should exist
singularity_image: /cellar/users/aklie/opt/gene_program_evaluation/src/inference/grn_models/scenic+/envs/scenic+.sif # Optional
n_jobs: 1 # Threads
random_state: 1234

# pycistopic parameters
blacklist: https://github.com/Boyle-Lab/Blacklist/blob/master/lists/mm10-blacklist.v2.bed.gz
n_topics: '2;4;8;16;32;48'
n_iter: 150
alpha: 50
alpha_by_topic: TRUE
eta: 0.1
eta_by_topic: FALSE

# candidate enhancer parameters
ntop: 3000
scale_factor_impute: 1000000
scale_factor_normalize: 10000

# pycistarget parameters
tf_annotations: https://resources.aertslab.org/cistarget/motif2tf/motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl
tf_list: https://resources.aertslab.org/cistarget/tf_lists/allTFs_mm.txt
rankings_db: https://resources.aertslab.org/cistarget/databases/mus_musculus/mm10/screen/mc_v10_clust/region_based/mm10_screen_v10_clust.regions_vs_motifs.rankings.feather
scores_db: https://resources.aertslab.org/cistarget/databases/mus_musculus/mm10/screen/mc_v10_clust/region_based/mm10_screen_v10_clust.regions_vs_motifs.scores.feather
run_without_promoters: FALSE

# SCENIC+ parameters
biomart_host: "http://sep2019.archive.ensembl.org/"
min_distance_upstream: 1000
max_distance_upstream: 150000
min_distance_downstream: 1000
max_distance_downstream: 150000
