# Configuration file for SCENIC+
input_loc: /cellar/users/aklie/opt/gene_program_evaluation/src/tests/test_data/neurips.small.h5mu
organism: human # human or mouse
outdir: /cellar/users/aklie/tutorials/gene_program_evaluation/scenic+/neurips2021/small # Created if doesn't exist.
scratchdir: /cellar/users/aklie/tmp # Should exist
singularity_image: /cellar/users/aklie/opt/gene_program_evaluation/src/inference/grn_models/scenic+/envs/scenic+.sif # Optional
n_jobs: 1 # Threads
random_state: 1234

# pycistopic parameters
blacklist: https://www.encodeproject.org/files/ENCFF356LFX/@@download/ENCFF356LFX.bed.gz
n_topics: '2;4;8;16;32;48'
n_iter: 150
alpha: 50
alpha_by_topic: TRUE
eta: 0.1
eta_by_topic: FALSE

# candidate enhancer parameters
ntop: 3000
scale_factor_impute: 1000000
scale_factor_normalize: 10000

# pycistarget parameters
tf_annotations: https://resources.aertslab.org/cistarget/motif2tf/motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl
tf_list: https://resources.aertslab.org/cistarget/tf_lists/allTFs_hg38.txt
rankings_db: https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/screen/mc_v10_clust/region_based/hg38_screen_v10_clust.regions_vs_motifs.rankings.feather
scores_db: https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/screen/mc_v10_clust/region_based/hg38_screen_v10_clust.regions_vs_motifs.scores.feather
run_without_promoters: FALSE

# SCENIC+ parameters
biomart_host: "http://sep2019.archive.ensembl.org/"
min_distance_upstream: 1000
max_distance_upstream: 150000
min_distance_downstream: 1000
max_distance_downstream: 150000
