input_loc: path/to/mudata/mudata.h5mu
prog_key: prog # mudata key for anndata containing cellwise program scores
data_key: rna # mudata key containing data used to estimate programs
batch_key: batch # obs key containing batch annotation
rna_key: rna # Typically same as data_key
atac_key: # Leave empty if no atac data
organism: human # human or mouse
database: enrichr # enrichr or msigdb for gene sets
library: Reactome_2022 # library of gene sets
workdir:  path/to/working/directory/ # Created if doesn't exist.


