# Configuration file for my_grn_model
input_loc: /cellar/users/aklie/opt/gene_program_evaluation/src/tests/test_data/neurips.small.h5mu
organism: human # human or mouse
outdir: /cellar/users/aklie/tutorials/gene_program_evaluation/scenic+/neurips2021/small # Created if doesn't exist.
scratchdir: /cellar/users/aklie/tmp # Should exist
singularity_image: /cellar/users/aklie/opt/gene_program_evaluation/src/inference/grn_models/scenic+/envs/scenic+.sif # Optional
n_jobs: 1 # Threads
random_state: 1234

# step 1 parameters

# step 2 parameters

# So on